# Generated by Django 4.1.5 on 2023-01-10 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.customer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.assetcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='unitIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UnitIN', to='inventory.assetunit'),
        ),
        migrations.AddField(
            model_name='asset',
            name='unitOUT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UnitOUT', to='inventory.assetunit'),
        ),
    ]
