# Generated by Django 4.1.5 on 2023-01-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10)),
                ('request', models.CharField(max_length=128)),
                ('medicalhistory', models.CharField(max_length=128, null=True)),
                ('health', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'Consulting',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('date_apply', models.DateField(max_length=10)),
                ('date_end', models.DateField(max_length=10, null=True)),
                ('note', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Treatment',
            },
        ),
        migrations.CreateModel(
            name='TreatmentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField()),
                ('date', models.DateField(max_length=10)),
                ('status', models.TextField(max_length=128)),
                ('tmp_thumb', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'TreatmentProcess',
            },
        ),
        migrations.CreateModel(
            name='TreatmentProcessImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treat', models.IntegerField()),
                ('treat_pro', models.IntegerField()),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='Treatments')),
            ],
            options={
                'db_table': 'TreatmentProcessImages',
            },
        ),
    ]
